# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: id_grp3
instance_flavor: uom.mse.2c9g
hosts_file_absolute_path: /mnt/c/it_project/COMP90024_Ass2/ansible/inventory/hosts.ini

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 100
  - vol_name: vol-2
    vol_size: 100
  - vol_name: vol-3
    vol_size: 100
  - vol_name: vol-4
    vol_size: 100

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-1
    volumes: ['vol-1']
  - name: instance-2
    volumes: ['vol-2']
  - name: instance-3
    volumes: ['vol-3']
  - name: instance-4
    volumes: ['vol-4']



